# Created 2024-07-13 Sat 16:00
#+options: toc:nil
#+options: todo:nil
#+latex_header: \usepackage{setspace, ragged2e, lineno, alphabeta, draftwatermark, textcomp, siunitx}
#+latex_header: \renewcommand{\linenumberfont}{\normalfont\bfseries\tiny\color{blue}}
#+latex_class: apa7
#+csl-style: apa.csl
#+latex_class_options: [stu, floatsintext, a4paper]
#+bibliography: proposal.bib

\linenumbers
\SetWatermarkLightness{0.9}
\SetWatermarkScale{1}

*234.327 Research Proposal*

*Title:* The Impact of Static and Dynamic Stretching on Vertical Jump Performance: A Comparative Study.

*Student Researchers:* David Peacock, Brad Cook

*Supervisor:* Professor Ajmol Ali - School of Sport, Excercise, and Nutrition.

* Introduction

** Background

Stretching is a fundamental component of athletic preparation (ref). Stretching before and after exercise may reduce muscle soreness, injury risk, and increase athletic performance (Dalrymple et al., 2010; Stojanovic et al., 2022); however, stretching alone is likely insufficient.

Stretching has been shown to produce small and non-significant reductions in muscle soreness 24 hours after exercising (Herbert & Gabriel, 2002). A recent study using military recruits who stretched prior to exercising showed no significant reduction in injury risk (Herbert & Gabriel, 2002); however, another study using elite soccer players showed significantly fewer injuries when following a routine of stretching combined with a warm-up compared to another group with no intervention (Kirmizigil et al., 2014).

The two common stretching modalities are static stretching (SS) and dynamic stretching (DS) (Carvalho et al., 2012). SS involves holding a muscle in an elongated position for a prolonged duration (typically 20-30 secs) (ref). SS typically improves flexibility, increases range of movement, and can reduce muscle soreness (ref). SS has been shown to have a negative effect on power (Warneke et al., 2024). Conversely, DS involves controlled repetitive movements that mimic the activity about to be performed, for example, leg swings or arm circles (ref). DS increases blood flow and can enhance neuromuscular activation (ref). DS has been shown to be better preparation for plyometric activities like jumping (Warneke et al., 2024).

** Justification

This study intends to contribute to existing literature. Previous studies have provided conflicting or insignificant results (Warneke et al., 2024), making comparisons difficult. These differences may be due to variability in stretching protocols, lack of control groups, differences in athletic ability between studies, and methodological variations. This study attempts to bridge or eliminate some of these conflicts. This will be a randomised, controlled, cross-over study using a simple and effective measure for vertical jump. By directly comparing SS and DS of the same muscle groups and their effect on vertical jump performance against a control, we intend to provide a robust argument for which stretching protocol provides the best performance benefit for power-based activities. This will allow coaches and athletes to create evidence-based warm-up routines to optimise performance and potentially minimise injury risk.

** Aims and objectives

Our Null Hypothesis (H_{0}) is that there is no significant difference in vertical jump performance between static and dynamic stretching of major leg muscles, and our Alternative Hypothesis (H_{1}) is that there is a significant difference in vertical jump performance between static and dynamic stretching of major leg muscles.
* Overview of project

** Study design

This study will compare the effect of two popular stretching modalities on vertical jump performance using a randomised, controlled, cross-over design.
Participants will be assigned a random number and then split into three groups: A, B, and C. This process will anonymise individuals, randomise the study, and provide the basis for the cross-over design.

All participants will conduct a warm-up as prescribed below, followed by a pre-stretch jump (PRE). One group will then conduct static stretching (SS), one group will conduct dynamic stretching (DS), and as a control, one group will conduct no stretch, passive rest (NS). They will then all conduct a post-stretch jump (POST). On the next testing day, each group will conduct a different protocol, so over three testing days, all groups have conducted all protocols, including control. The difference, if any, of the stretch protocols will be described and then compared to the rest control. This cross-over design will create self-control and eliminate individual differences in jump performance.

** Familiarisation and main trials

No familiarisation trials are required as all participants will have three attempts at each jump - with the highest jump being recorded- and they will conduct all stretching modalities over the entire testing period.

** Ethics approval/procedures

Ethics approval will be sought through Massey University's ethics process.

* Procedures

** Specific information relating to methods

    1. The activity will be conducted on as consecutive days as possible in the exact location at the same time of day to reduce remarkable differences in ambient temperature and humidity. Daily temperature will be recorded and noted.
       
    2. All participants should be physically fit (according to the self-assessment form on the day of testing) and engage in regular fitness activities, including jumping.
       
    3. Participants will conduct the test wearing light-weight sports clothing and without shoes (socks may be worn).
       
    4. All participants will be allocated a number to provide anonymity and then put into one of three groups (this number and group will be used throughout the testing process).
       
    5. The initial warm-up consists of three minutes on an ergometer indoor rowing machine, which is approximately 500m (or equivalent aerobic warm-up such as light jogging shuttles).
       
    6. Each participant will then conduct three attempts at a vertical jump using the Vertec, with the highest jump being recorded.
       
    7. The NS group will then passively rest for three minutes after the initial warm-up.
       
    8. For three minutes, the SS group will perform static stretches targeting major leg muscle groups (e.g., hamstrings, quadriceps, calves).
       
       
    9. For the same duration, the DS group will engage in dynamic stretches targeting the same muscle groups (e.g., knee-grab glute stretch, foot-grab quad stretch, then single-leg floor scoop combination and calf pumps).
       
    10. Each participant will then get another three jumps using the Vertec, again with the highest jump being recorded.
	
** Equipment/procedures/techniques used

Equipment required is a Vertec vertical jump tester, a measuring tape suitable for measuring individuals' vertical reach and jump height, and an ambient temperature thermometer. Although out of the scope of this research, body mass may be measured using body mass scales if individuals want to independently assess their peak power using the calculation provided below. A suitable location will be sought, ideally indoors with a firm floor and maneuverable space. Enough rowing ergometers for all participants will be available, or space will be available to conduct a comparable light aerobic warm-up using jogging shuttles.

All participants will have completed the /Participant Information and Permission form/ prior to conducting any of the testing processes. On the testing days, participants will complete the /Participant Pre-testing Self-assessment form/. On the first day, all participants will have their age and sex recorded, be allocated a random number, and then be allocated to one of three groups (A, B, or C). These numbers and group allocations will be used for the duration of the testing process.

The warm-up process will consist of either three minutes (approximately 500m) of light exercise on a rowing ergometer or three minutes of jogging shuttles - enough to elevate the heart rate above rest and create local muscle warmth but not to fatigue the participants.

The Vertec vertical jump tester will be used according to the manufacturer's instructions. Individuals will stand under the Vertec, feet together with their dominant hand stretched up. The Vertec will then be adjusted so the bottom-most measuring tab touches the furthest tip of the outstretched fingers - this is the starting point. The individual will then jump by semi-squatting, not letting the knee joint flex beyond 90, with the arms, hands, and fingers straight and behind the torso. The individual will pause in this position to prevent any counter movement, then extend the legs and hips, and at the same time swing the arms out in front and then up over the head to swipe the Vertec measuring tabs at the peak of the jump movement using their fingers. The measuring tabs that were touched will then be moved out of the way, and after a 10-second rest, another jump is attempted. If further tabs are touched, the jump was higher than any previous jumps from that individual, and if none were touched, then the jump was lower than the highest previous jumps. After three attempts, the highest jump is measured using the remaining tabs. All tabs are then reset, and the process is repeated with the following individual.

After all participants have completed the pre-stretch jump, they will concurrently conduct the stretching protocol allocated to their group. The SS protocol consists of a one-legged standing quadriceps stretch by flexing the knee of one leg and pulling and holding the foot against the buttocks. The individual should feel the stretch in the mid-thigh area; if needed, the hip can be extended and held to further increase the stretch until it is felt in the quadriceps. The gluteal and hamstrings are stretched by standing upright, crossing one foot in front of the other, bending over by flexing at the hips, keeping the rear-most knee straight, and attempting to touch the floor. The stretch should be felt in the hamstrings and glutes of the leg with the foot behind the other. The individual may slightly bias their bodyweight to one or other side to increase the stretch until it is felt in the hamstring. The calf is stretched by being prone and supported on outstretched arms as at the start of a press-up, and then place one foot on top of the other and flex the ankle of the foot on the ground, keeping both knees straight. This action should stretch the gastrocnemius and soleus muscles and the Achilles tendon and be felt in the belly of the calf. The hands can be 'walked' towards the feet, lifting the buttock higher to increase the stretch if required. The stretches are then repeated on the other leg. All stretches are held static for 30 seconds without bouncing or releasing. These protocols provide three minutes of static stretching.

The DS protocol consists of a standing one-legged quadriceps stretch as described in the SS protocol; however, once the stretch is felt, the foot is released, and after taking one step, the stretch is repeated on the other leg. This alternating process continues for one minute. The gluteals and hamstrings are stretched by placing one foot slightly in front of the other, and by flexing the ankle and keeping the heel on the ground, the sole is raised. Then, keeping both knees straight, the participant flexes at the hips and bends over, and in the same motion with arms straight, makes a scooping motion by brushing the fingers on the ground from rear to front. Then after a step, the process is repeated using the other foot and continues for one minute. The calves are stretched in the prone position supported on outstretched arms like the start of a press-up, and the hips are then raised slightly. The ankle on one leg is flexed, and the knee is bent slightly, causing a stretch that is felt in the calf. The ankle is then relaxed and the knee straightened before repeating on the other leg. This process continues alternating between legs, causing a foot 'pumping' motion for one minute.

The NS protocol consists of passive rest for three minutes.

Once all groups have completed their stretching protocol, the jump assessment process is repeated, and the highest of the three post-stretch jump attempts for each individual is recorded.

** Add schematic diagram (if appropriate)

Not required?

* Statistical approaches

** Data Collection

Data will be collected and tabulated in a CSV file for analysis using R Statistical Software (R Core Team, 2021). The difference between the pre-stretching and post-stretching jumps for each stretching protocol will be calculated. Initial descriptive statistics (mean, median, SD, range, IQR, skewness, kurtosis) will be assessed and reported.

** Assumption Checks

The following assumption checks will be carried out: normality using Shapiro-Wilk test and Q-Q plot and sphericity using Levene's test for equal variances. Independence is built into the testing protocol and is required for future analysis of variance (ANOVA).

** Analysis

A repeated measures ANOVA will provide comparisons between the two stretching protocols and the non-stretching control.

** Post hoc Analysis

/Post hoc/ analysis will consist of Tukey's HSD (if equal, there is variance amongst each category [Levene's Test]). Any statistically significant results will be assessed with pair-wise two-tailed t-tests with Holm-Bonferroni correction to reduce type I (false positive) errors. The effect size will be calculated with partial eta-squared (\eta_{p}^{2}), ideally > 0.5. Degrees of freedom (df) for treatment (number of conditions - 1) and degrees of freedom (df) for error (number of participants - 1) will be calculated. A confidence interval (CI) of 95% will be used, the critical value calculated (t-value if samples\nbsp{}<\nbsp{}30 and z-value if samples\nbsp{}>\nbsp{}30), and the margin of error (ME) will be evaluated. If, during Levene's test, variance is assessed as unequal, a linear mixed model may be used. Statistics will be presented as mean \pm standard deviation, and an \alpha = 0.05 will be used throughout.

** Plots

Data will be presented visually using a bar chart or /box-and-wisker/ chart of protocols compared, highlighting any statistical differences. An interaction plot may also be used if relevant.

* Participant Involvement

** Sample size

If a power of 80% is desired, an estimated sample size of between 15 and 30 participants will be required depending on the hypothesised difference and population variance. As the same participants will be used across all conditions (cross-over), this reduces variability caused by individual differences and allows for fewer participants. Actual power will be calculated once data is collected.

** Who are the participants?

Participants are intended to be recruited by word-of-mouth from a local all-star cheerleading team and who will have an interest in human performance and sports science. These athletes are of similar training backgrounds and are predominantly female, between 11 and 17 years old, usually fit and healthy, and regularly engage in plyometric activities. As they are minors, parental permission is required and will be indicated by a parent or guardian signature at the end of the Participant Information and Permission form. Participants will be asked to have at least 7 hours rest in bed the previous night, abstain from alcohol 24 hours prior, reduce caffeine intake that day, and not consume any performance-enhancing medication or drugs prior. Participants are asked to eat as usual that day before conducting the activity.

** Inclusion/exclusion

Participants are required to have no current injuries preventing vertical jumping as declared on the /Participant Pre-testing Self-assessment form/. Minor participants (<18 years old at the time of testing) must have documented parent or guardian permission before any testing procedure.

* Further Information

** Any other information relating to the project
    1. All statistical analysis will be conducted using R Statistical Software (v4.2.3, R Core Team 2024).

* References

Carvalho, F. L. P., Carvalho, M. C. G. A., Simão, R., Gomes, T. M., Costa, P. B., Neto, L. B., Carvalho, R. L. P., & Dantas, E. H. M. (2012). Acute Effects of a Warm-Up Including Active, Passive, and Dynamic Stretching on Vertical Jump Performance. /The Journal of Strength & Conditioning Research/, 26(9), 2447. https://doi.org/10.1519/JSC.0b013e31823f2b36
Dalrymple, K. J., Davis, S. E., Dwyer, G. B., & Moir, G. L. (2010). Effect of Static and Dynamic Stretching on Vertical Jump Performance in Collegiate Women Volleyball Players. /The Journal of Strength & Conditioning Research/, 24(1), 149. https://doi.org/10.1519/JSC.0b013e3181b29614
Herbert, R. D., & Gabriel, M. (2002). Effects of stretching before and after exercising on muscle soreness and risk of injury: Systematic review. /BMJ/, 325(7362), 468. https://doi.org/10.1136/bmj.325.7362.468
Kirmizigil, B., Ozcaldiran, B., & Colakoglu3, M. (2014). Effects of Three Different Stretching Techniques on Vertical Jumping Performance. /The Journal of Strength & Conditioning Research/, 28(5), 1263. https://doi.org/10.1519/JSC.0000000000000268
R Core Team. (2021). /R: A language and environment for statistical computing/ [Computer software]. R Foundation for Statistical Computing. https://www.R-project.org/
Stojanovic, M., Mikić, M., Vlatko, V., Belegišanin, B., Aleksandar, K., Bianco, A., & Drid, P. (2022). Acute effects of static and dynamic stretching on vertical jump performance in adolescent basketball players. /Gazzetta Medica Italiana/, 181, 417–424. https://doi.org/10.23736/S0393-3660.20.04575-1
Warneke, K., Freundorfer, P., Plöschberger, G., Behm, D. G., Konrad, A., & Schmidt, T. (2024). Effects of chronic static stretching interventions on jumping and sprinting performance–a systematic review with multilevel meta-analysis. /Frontiers in Physiology/, 15, 1372689. https://doi.org/10.3389/fphys.2024.1372689
